services:
  - type: web
    name: resolveit
    runtime: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: "8080"
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: "resolveit_db"
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_MODE
        value: "true"
      - key: JAVA_OPTS
        value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
